AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
                KMSMasterKeyID: aws/kms
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 7
          Status: Enabled
        - NoncurrentVersionExpirationInDays: 1
          Status: Enabled
        - ExpirationInDays: 1
          Status: Enabled
      ObjectLockEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
      AccelerateConfiguration:
        AccelerationStatus: Enabled
      LoggingConfiguration:
        DestinationBucketName: arn:aws:s3:::loggingbucket
        LogFilePrefix: log
      Tags:
        - Key: Environment
          Value: SecJam
        - Key: Role
          Value: Challenge
        - Key: Owner
          Value: Trend-Micro
        - Key: Name
          Value: Challenge-Bucket
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Id: Challenge-Bucket-Policy
        Statement:
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: AES256
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - Fn::GetAtt S3Bucket.name
                - /*
            Condition:
              'Null':
                s3:x-amz-server-side-encryption: 'false'
          - Sid: ForceSSLOnlyAccess
            Effect: Deny
            Principal:
                AWS: "*"
            Action: s3:PutObject
            Condition:
              Bool:
                aws:SecureTransport: false
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
Description: ''
Outputs:
  S3BucketName:
    Value: !Ref S3Bucket